#!/bin/bash
#This script is executed every time your instance is spawned.

# copy files to home folder
cp -af ~/my_data/home/. ~/

# setup ssh keys
chmod 700 ~/.ssh/
chmod 600 ~/.ssh/*

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins
