#!/bin/bash
#This script is executed every time your instance is spawned.

# copy files to home folder
cp -af ~/my_data/home/. ~/

# setup ssh keys
chmod 700 ~/.ssh/
chmod 600 ~/.ssh/*

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins

echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSetup Complete\nLog in using the following command: \n\nssh $USER@$HOSTNAME.htb-cloud.com\n"
