[font]
size = 16.5

[window]
padding = { x = 10, y = 10}
dynamic_padding = true
decorations  = "None"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
   "~/.config/alacritty/dracula.toml"
]
